name: TimingSystemBlueMap
version: 0.0.1-SNAPSHOT
authors: [Justin Brubaker (JustBru00)]
softdepend: [TimingSystem,BlueMap]
main: com.frosthex.timingsystem.bluemap.TimingSystemBlueMapPlugin
api-version: 1.19

