name: TimingSystemBlueMap
version: 0.0.2
authors: [Justin Brubaker (JustBru00)]
softdepend: [TimingSystem,BlueMap]
main: com.justbru00.timingsystem.bluemap.TimingSystemBlueMapPlugin
api-version: 1.19

